db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3307/tecnicentro?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Guayaquil&characterEncoding=UTF-8
db.usuario=root
db.password=1234